language: generic
sudo: required
services: docker
branches:
  only:
    - master
env:
  global:
  - PROJECT_NAME=lpp-payment
  - PROJECT_VERSION=1.0.0
  - DOCKER_USERNAME=bezpov
  - secure: X2/Pq4ef0Gme7qziSmy3MzQZ47NKYaxPEn1Rn0wcx9Gtf9tn+cwFTnCuEdz4QenLOEYVxefLKGf5C4B0ZyTBaaX9hhU9co0iL8gltpYNGERWktcf/gS/rj14rTWIfFLmHHRJ1TJZqIqwKZrxfOjAINNO7GsIuzRNemg14SMLHg+BKfcRNx5zjX2GIxK6IebsIW4RdLEwZvgTwFdgFwhyMGB7dZkUfVietHONoQE+c/I7/m/FZVmUDOXDlGQmmWgOnDr18JtdDPh842FiYdDQ/WGSM5Ps0IWfqlEsMVLsRuii751n8LU2vvIshMPWezWPG42I+YvHTh3uYOwK2mbHrVBwvDKa7sqeHCSCvIM/GD+/alGLRxJEf+LxEasah3WJuBhwcRJWUoIvRhzQx/YYvr4xjadPioqA+yFVuM+YXIUspN+llQrHbqNltGw0fFlY8aXVDOy+G0YUszA7SYvwtN90WUJaWhDVolLgaT5Ky5AF2LyYoqwv2begXfP4O8A/4x3vdjaijaTTyT8gAtEd/K6WgXaZIlaiLLaP46OfiypGQokPvnpA1CiZWfo1OdGW/dmDaQuJ0dHvsn/zuK0l9/ueVN7mtgBt0ndUWNFnRNZ4OuzHbQcRGWECt96GMMHcDzJCbUCCxfrnLigvAAvXNPYE68XmEs/DswSAMzKp8BY=
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
