apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpp-payment
spec:
  selector:
    matchLabels:
      app: lpp-payment
  replicas: 1
  template:
    metadata:
      labels:
        app: lpp-payment
    spec:
      containers:
        - image: bezpov/lpp-payment:1.1.0
          name: lpp-payment-container
          env:
            - name: ETCD_SERVER
              value: "http://etcd-client:2379"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lpp-payment-service
  namespace: default
  labels:
    app: lpp-payment
spec:
  ports:
    - protocol: TCP
      port: 85
      targetPort: 8080
  selector:
    app: lpp-payment
  type: NodePort